### ISSUE TITLE
Observing IPSO composite objects

### ISSUE THREAD

**Issue by gmazzoleni** [IPSO-Alliance/pub#28]
Hello to everybody,
I am quite new to LWM2M and IPSO objects and I have some doubts that hope you could clarify.

I would like to implement multiple sensors (light, pressure, temperature, ...) on a constrained device.
I would like to describe the various sensors following the IPSO structure (value, unit, min, max, clear, ...)

The device should periodically (1-10 mins) notify an observer of the updated values with a **single message**.
The message would only need to contain the values of the various sensors and not the other resources.

This is similar to what has already been asked time ago by Darko in https://github.com/IPSO-Alliance/pub/issues/5

1. I could probably create a composite object with links to the various objects, but then is it allowed in LWM2M to return just the values of the pointed objects in a single notification message (TLV or JSON)? And would it still be possible to observe the whole composite object?

2. I could also create a custom object (but I would rely on it only if no other standard way could be achieved).

Am I missing something? Do you suggest any particular approach?

Many thanks for any suggestion you could provide.
Best regards,
Giulio

**Comment by gmazzoleni** [comment]
Is it correct that returning multiple objects into a single notification message is only supported by the JSON format and not by the TLV one?

I am taking as reference the following sentences from the OMA-TS-LightweightM2M-V1_0:

> TLV (sect. 6.4.3.3)
> The TLV format doesn‟t report Object hierarchy
> 

> JSON (sect 6.4.4)
> In particular, when Base Name is set to the LwM2M Object root (e.g., “/”), the JSON format may support to return a hierarchy of Object Instances when Object Link datatype resources are reported

By using JSON would it be allowed to return just some of the resources of the linked objects, but not all of them?

**Comment by mjkoster** [comment]
The approach I took in the proposed lighting objects is an object type that makes a local "link group" (used to be called "batch object").

See object 3010 in the proposal:
https://github.com/mjkoster/lighting-objects/blob/master/docs/lighting-objects.md

There is one resource that contains an array of object links and another that contains an array of instances that serve as proxies to the observed objects. 

For selecting resources to report inside each object, we would need to create a resource link type to use instead of the object type, and for this I would propose to use a hyperlink (resource ID 5018, Target IRI, could be used, should be string type, not boolean, and allow multiple instances).

The proposed link group object extension would allow multiple instances of a type 5018 resource to be used to point to resources and would return only the resources linked in notification payloads.

If the desired behavior is to only return the resources that have changed (vs. all linked resources) then there could be some behavior flag to indicate this.

**Comment by mjkoster** [comment]
The Observe protocol in CoAP will, by definition, repeat the GET response on each notification.

The SenML response would put the unique resource paths in the "n" elements. 

I don't know how TLV encoded responses would look.

**Comment by jaimejim** [comment]
As there aren't more comments I'll close the issue.
