### ISSUE TITLE
Can we group sensors value into one object?

### ISSUE THREAD

**Issue by darkopetrovic** [IPSO-Alliance/pub#5]
Hello,

I wonder if with the OMA LWM2M protocol it is possible to group sensors value into one object? 

I've a device with several sensors and I'm using Contiki. Since we have a finite number of observers at the same time on a Contiki device (configurable but not so much possible because of memory constraint), can we manage to group sensors value into one representation? Does the protocol provides such possibility so that an observer can retrieve all sensors value on the device at the same time?

Technically, we'd have a response maybe like this doing a GET on a custom resource:

```
{"e":[{"n":"3303/0/5700","v":"25.00"},{"n":"3304/0/5700","v":50.00},{"n":"3301/0/5700","v":1500},{"n":"3315/0/5700","v":60000},{"n":"3314/0/5700","v":2000}]}
```

Is this permitted? Is it a better solution?
Thanks.

**Comment by jaimejim** [comment]
Just to make sure I understand, you have a custom object that is composed of the mandatory resources of several other objects, right? 

First of all LWM2M is used on the management plane with a very specific set of objects. For applications you wouldn't use LWM2M (although you could) but you'd use plain CoAP instead. Application data (i.e. sensor/actuator readings/commands) is specified using the IPSO Object Model, which differs form OMA's in just few things. One of those things is the ability to do composition: https://github.com/IPSO-Alliance/pub#Composite%20Objects 

One option is to do independent observations to each Object, that way you could just use LWM2M. Another option is to implement Object Composition instead of nesting resources. Then you can do a CoAP GET (Observe=0) to the new composite object (composed of object links to the other objects). That should signal the server that, if a resource is an object link, you want to observe the object it is linking to.

**Comment by darkopetrovic** [comment]
Hello Jaime,

thanks for the answer.

I have nothing actually :) I'v just discovered the LwM2M protocol with the IPSO smart object definition and I was wondering if we can somehow retrieve the sensors value of a device at once while keeping the interoperability. 

Ideally yes, I'd have a custom object composed of the mandatory resources of the sensors object listed in the IPSO starter pack. 

I'v found the Composite Objects this could be the solution but I'm not quite sure yet how this is flexible, there is very little example. In the example for the Thermostat presented in the documentation, can we link resource ID `/3303/0/5700` directly? What does this object link means exactly? Is that at the implementation level or this is just a definition for the new Composite Object? 

Thanks.
Darko

**Comment by jaimejim** [comment]
Object Link is just two integers pointing to a resource within the same device separated by a colon.  "ObjectID:ObjectInstance"

In the future those should be changed to proper hyperlinks.

**Comment by moleike** [comment]
@jaimejim just nitpicking but:

> First of all LWM2M is used on the management plane with a very specific set of objects. For applications you wouldn't use LWM2M (although you could) but you'd use plain CoAP instead. Application data (i.e. sensor/actuator readings/commands) is specified using the IPSO Object Model, which differs form OMA's in just few things. One of those things is **the ability to do composition**: https://github.com/IPSO-Alliance/pub#Composite%20Objects

[emphasis mine]

But in **OMA-TS-LightweightM2M-V1_0-20170208-A** does specify Object Link data type for resources and gives examples for both TLV and JSON.

Are these different things?

P.S. Sorry for commenting in a closed issue.
